### ISSUE TITLE
Informatiebehoefte bij een specificatie

### ISSUE THREAD

**Issue by ElisabethKloren** [bimloket/COINS-3.0-Contract-als-data#10]
Vraag aan deelnemers gebruikersbijeenkomst COINS 3.0 Contract als data op 3 april 2020:

Welke informatie is nodig bij de specificatie? Wat is minimaal, wat is nice to have?

~ Eistitel
~ Eistekst
~ Toelichting op de eis
~ Unieke identificatie over projecten heen / relatie naar bron: eis in eisenbibliotheek. 
~ Projectnummer / Communicatiecode (voor gesprek tussen twee personen in het project over de specificatie is een GUID niet zo geschikt)
~ Voorgeschreven verificatiemethode(s)
~ Voorgeschreven verificatiemoment(en)
~ Relatie met object óf activiteit óf functie óf informatieproduct

Nice to have
~ Geëiste waarde / min-max waarde / formule / uitkomst
~ Absolute en relatieve betrouwbaarheid van de gemeten waarde
~ Relatie met eigenschap van een object

~ Eistype is m.i. niet nodig, maar goed: is hier een landelijke standaard nodig of wordt dit per opdrachtgever / project bij elkaar gefantaseerd?

**Comment by redmer** [comment]
- Minimaal de informatie die nodig om terug te leveren naar de opdrachtgever. Daarmee ook OG-afhankelijk.

**Comment by martinevandalfsen** [comment]
identiek aan in ieder geval het eisen blok van zowel een VSE als ook een VSP met de correcte onderlinge relaties

**Comment by thomasmunster** [comment]
het hangt af van wat je met de eis gaat doen, welke informatie je er aan wilt koppelen. 
gaande een project worden eisen gemuteerd, vervallen, geverifieerd, overgedragen, etc. 
over al deze processen wil je elkaar op de hoogte houden in iedere OG/ON relatie.

**Comment by ElisabethKloren** [comment]
User story voor beheercommissie:

1.	Omschrijving van de vraag/opmerking zelf (bij voorkeur in het format van ‘userstory’):
Als  opdrachtnemer van een bouw- of onderhoudsproject
wil ik  alle onderdelen uit het contract, die ik moet aantonen als data ontvangen, waaronder de eisen, raakvlakken in Vraagspecificatie Proces, Vraagspecificatie Eisen, Informatieleveringsspecificatie
zodat ik  deze direct kan inlezen in mijn projectbeheersingssysteem en ik de kosten en risico's van de uitvraag sneller kan bepalen
2.	Naam, functie (soort gebruiker/rol), diens organisatie, en de soort organisatie van de vraagsteller (stakeholder): deelnemers gebruikersbijeenkomst Contract als data 3 april 2020
3.	Datum en oorsprong van het verzoek: Uit gebruikersbijeenkomst Contract als data 3 april 2020
4.	Wat is de urgentie  )
‘M’	(must have; hindert de dagelijkse procesgang/doorgang van een project; moet zo spoedig mogelijk worden opgelost)
5.	Toelichting op de urgentie - de levering van het contract als data gaat veel tijd en kosten besparen ook voor de opdrachtgever.

Voeg meer details toe:
1.	Het betreft een ‘verbetervoorstel

3.	Verbetervoorstel
a.	Maak de userstory expliciet; mogelijk valt die uiteen in meerdere user stories 
- 
b.	Beschrijf de randvoorwaarden 
- De gebruikers denken aan een basisset die de meeste opdrachtgevers gebruiken, het SE-BIM model is véél te uitgebreid, daarmee wordt de vraag te complex.
c.	Completeer de ‘definiton of ‘done’ 
Als de eisen, risico's en raakvlakken Vraagspecificatie Eisen, Proces en Informatieleveringsspecificatie geleverd kunnen worden als dataset.
