### ISSUE TITLE
Doel Contract als data

### ISSUE THREAD

**Issue by ElisabethKloren** [bimloket/COINS-3.0-Contract-als-data#3]
Doel: Uitvragen, contracten voor ontwerp-, bouw- en onderhoudscontracten aanbieden als data zodat opdrachtnemers deze kunnen importeren in hun projectbeheersingssystemen, kwaliteitssystemen.

**Comment by redmer** [comment]
Eerst houden bij **Vraagspecificatie eisen, resultaatspecificaties, en proceseisen, eisen aan informatieproducten**, andere documenten als ontwerptekeningen komen later.

**Comment by ElisabethKloren** [comment]
Hiervan wordt wel gezegd: haal wel alle informatie uit de VS1, ook al zit dit nog niet in het eenvoudige informatiemodel. Bijvoorbeeld raakvlakken. Tenminste de zaken die moeten worden aangetoond. Dit vraagt om een werkinstructie bij het opstellen van een contract-als-data.

**Comment by mrtnvssr** [comment]
Doel lijkt mij het eenvoudig kunnen overdragen van alle contractdata in de VS1. ON moet op deze data kunnen vertrouwen dat deze gelijk is aan pdf (zie #11 )

**Comment by ElisabethKloren** [comment]
Doelstelling wordt: De eisen, raakvlakken en risico’s in de Vraagspecificatie Eisen, Proces en de Informatieleveringsspecificatie eenvoudig kunnen leveren aan opdrachtnemers zodat deze direct kunnen worden ingelezen in projectbeheersingssystemen.
