### ISSUE TITLE
Specificaties aan functies

### ISSUE THREAD

**Issue by ElisabethKloren** [bimloket/COINS-3.0-Contract-als-data#5]
Vragen aan de deelnemers van de gebruikersbijeenkomst Contract als data op 3 april 2020:
Hoe worden specificaties aan functies aangeboden door opdrachtgevers in de uitvraag of na gunning?
~ Contract, vraagspecificatie eisen in PDF;
~ Als CSV bestand of anderszins als data;
Hoe zijn de functies gedefinieerd? 
Hebben opdrachtnemers behoefte aan afspraken, standaarden of handleidingen?

**Comment by Tim-VI** [comment]
In veruit de meeste contracten wordt weinig over functies gesproken. In enkele contracten wordt een functieboom meegeleverd en kan de relatie naar objecten en/of eisen gelegd zijn. In sommige contracten is duidelijk dat de vraagspecificatie is opgezet vanuit de behoefte om functies vervuld te krijgen.

**Comment by nicoburgerhart** [comment]
zie ook http://publicaties.minienm.nl/documenten/instructie-modelleren-op-basis-van-de-otl-versie-2-4-gebruikershandleiding-bij-het-opbouwen-en-gebruiken-van-een-datamodel-voor-een-bim-projectdatabase-op-basis-van-de-otl-versie-2-3
H3 Decompositie van de Functionele Objecten

**Comment by RiX012** [comment]
> 
> 
> In veruit de meeste contracten wordt weinig over functies gesproken. In enkele contracten wordt een functieboom meegeleverd en kan de relatie naar objecten en/of eisen gelegd zijn. In sommige contracten is duidelijk dat de vraagspecificatie is opgezet vanuit de behoefte om functies vervuld te krijgen.

Dit is in de GWW sector zonder meer waar. Maar juist in andere sectoren (aerospace, processing) is juist de functie leidend. Hetgeen wat gerealiseerd moet worden op een bepaalde plek in tijd en ruimte.

Functies worden pas echt relevant in het kader van specificaties als deze ook 'individueel' gemaakt worden. Dus wanneer een prestatie gemeten moet worden. In sommige contractvormen (bijvoorbeeld prestatiecontracten) is dit het geval. 

Ook hier weer: het gebruik van functies is zo afhankelijk van de context. Daarmee is het het opnemen van Functies in gestandaardiseerde gegevens uitwisseling op zijn beurt weer afhankelijk van het beoogd gebruik. Dus eerst kijken of er uberhaupt generieke stappen te identificeren zijn en dan het uitwissel model zo simpel mogelijk houden.

**Comment by ElisabethKloren** [comment]
Functies worden opgenomen omdat deze toch gebruikt worden in de contracten, en duidelijk anders zijn dan activiteiten
