### ISSUE TITLE
Project- versus bibliotheek URI's

### ISSUE THREAD

**Issue by ElisabethDeVries** [bimloket/COINS-3.0-Contract-als-data#54]
MB zegt: 11. In par. 4.2 staat dat er is gekozen om alleen project-URI's te gebruiken, en geen bibliotheek/ontology-URI's: Ik zou het echter niet onmogelijk maken om dit te doen.

**Comment by ElisabethKloren** [comment]
Vanuit datatechnisch oogpunt: als je in een project dezelfde URI's gebruikt als in de bibliotheek, ga je in tegen de basisprincipes van linked data, iets waar je wel met de hele sector naar toe werkt; 

De herkenbaarheid van de eis voor de menselijke lezer kan wel in stand gehouden worden doordat je wel dezelfde [=EisCode=] kan gebruiken als in de bibliotheek.
