### ISSUE TITLE
Indentificatie, codes, hergebruik van informatie

### ISSUE THREAD

**Issue by ElisabethKloren** [bimloket/COINS-3.0-Contract-als-data#6]
Vragen aan de deelnemers van de gebruikersbijeenkomst Contract als data op 3 april 2020:

Hebben deelnemers behoefte aan afspraken, standaarden of handleidingen om te zorgen dat specificaties, objecten enzovoorts identificeerbaar zijn, op zo'n manier dat specificaties die in meerdere contracten gebruikt worden, herkend kunnen worden? Met als voordeel dat de verwerking in activiteiten, verificatie- en validatiestrategie enzovoorts van opdrachtnemer hergebruikt kunnen worden.

**Comment by Tim-VI** [comment]
Zeker. Alhoewel we willen leren over projecten heen en bibliotheken en best practices aan het vastleggen zijn, vinden we toch nog veel het wiel opnieuw uit. Eisen worden in iedere tender en vervolgens bij gunning opnieuw geanalyseerd en van een verificatiestrategie voorzien.

**Comment by redmer** [comment]
- Dezelfde eis - uit een referentiebron - wordt soms heel verschillend geformuleerd, waardoor je als opdrachtnemer goed moet opletten of het echt hetzelfde is, of dat er nuanceverschillen bestaan.
- **Bronverwijzing** of zelfs maar een inspiratiebron bij een enkele eis te vermelden, zou al een verbetering vormen. Dan zijn unieke eis-ID's niet eens zo nodig.

**Comment by mrtnvssr** [comment]
Interessant maar nice to have, stap 2.

**Comment by martinevandalfsen** [comment]
Indien er vragen zijn over de RWS basisspecificaties dan kunnen die gesteld worden aan daan.van.werven@rws.nl

**Comment by ElisabethKloren** [comment]
- Zie ook het project dat door VolkerWessels is ingediend bij de DiogiDeal: een bibliotheek van specificaties

**Comment by RiX012** [comment]
'Stukjes tekst' als uniek identificeerbaar aanbieden is gewoon erg lastig. Zeker omdat bepaalde woorden, begrippen of waarden in context gezien moeten worden. Wanneer we gaan naar 'aspect eisen' is dit beter te doen:
`Trottoir` `>` `2` `m` `breed`
Vooralsnog denk ik inderdaad dat een zwakke relatie als bronverwijzing the-way-to-go moet zijn.

**Comment by ElisabethKloren** [comment]
dit wordt verwerk in de documentatie
