### ISSUE TITLE
Specificaties aan processen/activiteiten

### ISSUE THREAD

**Issue by ElisabethKloren** [bimloket/COINS-3.0-Contract-als-data#7]
Vragen aan de deelnemers van de gebruikersbijeenkomst Contract als data op 3 april 2020:
Hoe worden specificaties aan processen/activiteiten aangeboden door opdrachtgevers in de uitvraag of na gunning?
~ Contract, vraagspecificatie eisen in PDF;
~ Als CSV bestand of anderszins als data;
Hoe zijn de processen/activiteiten gedefinieerd?
Zijn de activiteiten (indien van toepassing) gerelateerd aan objecten?
Hebben opdrachtnemers behoefte aan afspraken, standaarden of handleidingen?

**Comment by Tim-VI** [comment]
Een vraagspecificatie proces waarin wordt verwezen naar (bindende of gerefereerde documenten). 
Deze activiteiten worden gedefinieerd door de opdrachtgever. Dit kan zijn aan de hand van een IPM model, ISO15288 of naar eigen inzicht.
Dit standaardiseren zou fijn zijn omdat wij altijd de mapping maken (en de allocatie van proceseisen) naar ons eigen projectmanagement systeem en de onderliggende kwaliteitssystemen (van onze werkmaatschappijen).

**Comment by redmer** [comment]
- Een **standaard over opdrachten** (van dezelfde OG) en **opdrachtgevers heen** is gewenst.
  - Lastig te realiseren omdat verschillende projectteams daarvoor bijeen moeten komen en de SE-ervaring daar ook niet altijd aanwezig is.
  - Complexer ook dan objecttyperingen.
- Een standaard als onderdeel van/**horend bij een contractmodel** (zoals de _UAV-gc_) zou handig zijn. 
  - @ElisabethKloren Misschien een informatiemodel (_standaardstructuur_) voor te selecteren vanuit BIM-Loket

**Comment by ElisabethKloren** [comment]
Hiefvoor wordt een eerste eenvoudige oplossing beschreven in de documentatie
