### ISSUE TITLE
Specificaties aan informatieproducten

### ISSUE THREAD

**Issue by ElisabethKloren** [bimloket/COINS-3.0-Contract-als-data#8]
Vragen aan de deelnemers van de gebruikersbijeenkomst Contract als data op 3 april 2020:
Hoe worden specificaties aan informatieproducten aangeboden door opdrachtgevers in de uitvraag of na gunning?
~ Contract, vraagspecificatie eisen in PDF;
~ Als CSV bestand of anderszins als data;
Hoe zijn de informatieproducten gedefinieerd? Zijn deze gerelateerd aan objecten, functies en/of activiteiten?
Wordt metadata gevraagd bij de informatieproducten? Hoe wordt het informatiemodel hiervoor aangeleverd?
Worden koppelingen tussen informatieproducten gevraagd (foto's bij een object bijvoorbeeld?) Hoe wordt die relatie gelegd?
Hebben opdrachtnemers behoefte aan afspraken, standaarden of handleidingen?

**Comment by Tim-VI** [comment]
Alleen bij contracten met een ILS-achtig document wordt dit alles uitgevraagd. Bij het overgrote deel wordt dit echter niet gebruikt. Veelal zijn deze informatieproducten gedefinieerd in de VSE en niet direct gerelateerd aan objecten, maar als uitkomst bij een activiteit. Dan is er ook geen vraag om metadata.

Uiteraard is ook hier een standaard fijn. Als wij bijvoorbeeld niet bij iedere opdrachtgever de rapportage van het risicoregister hoeven aan te passen.

**Comment by redmer** [comment]
- Op dit moment verspreid tussen ILS, OTL en informatiemanagementspecificaties.
- @NielsHoffmann benoemt de samenwerking met het Nationaal Archief voor het Toepassingsprofiel metadatering overheden (TDMO) voor algemene metadatering ihkv de Archiefwet.
