### ISSUE TITLE
Instapniveaus "Contract als Data"

### ISSUE THREAD

**Issue by ElisabethKloren** [bimloket/COINS-3.0-Contract-als-data#9]
Vragen aan de deelnemers van de gebruikersbijeenkomst Contract als data op 3 april 2020:

Op welk instapniveau willen de deelnemers afspraken maken over contract als data? Of moeten er meerdere "Levels" zijn waarmee partijen verleid kunnen worden?

Vrij naar Tim Berners Lee, zie afbeelding onderin:

Niveau 1: PDF / ZIP-file met bestanden. 
~contract bijvoorbeeld Vraagspecificatie eisen, proces, informatieleveringsspecificatie in PDF,  referentie-ontwerp tekeningen in PDF

Niveau 2: Bestanden in native formaat van een softwareleverancier 
~ contract bijvoorbeeld Vraagspecificatie eisen, proces, informatieleveringsspecificatie in Excel; 
~ referentie-ontwerp in native bestanden, CAD, Revit, ...

Niveau 3: Bestanden in open formaat: CSV, IFC, Open GIS 
~ Contract bijvoorbeeld eisen aan objecten, processen, informatieleveringen in CSV; 
~ referentie-ontwerp in IFC, Open GIS 

Niveau 4: Linked data (RDF, OWL, SHACL et cetera) 
~ Contract bijvoorbeeld eisen aan objecten, processen, informatieleveringen in RDF
~ referentie-ontwerp in IFC, Open GIS (?)

Niveau 5: Linked Open Data met verwijzingen naar externe toegepaste informatiemodellen en databronnen. 
~ Contract bijvoorbeeld met herkenbare eisen uit een bibliotheek (van opdrachtgever of kennisinstituut), met links naar het referentieontwerp
~ Referentieontwerp in een gezamenlijke dataomgeving (Common Data Environment, naar ISO 19650) of in ICDD container met relaties tussen datasets en bestanden

![5-star-steps](https://user-images.githubusercontent.com/48585720/77414866-ed906380-6dc1-11ea-9ed3-3c75fc1ee954.png)

**Comment by redmer** [comment]
- Informatiemodel van _Relatics_ wisselt per project en opdrachtgever/-nemer. Dat is de kracht ervan, maar de betekenis van die data daarmee niet gewaarborgd. 
- Bij het project DIA (?) bevat een levering naast de contractdata zelf, ook het informatiemodel zelf. 
- Ervaringen met geuniformeerde data eerder (vanuit COINS ?) versimpelde tot eis, object, functie. Maar aspecten en raakvlakken, vallen daarmee buiten de boot en zouden dan alsnog in de PDF terechtkomen?

**Comment by martinevandalfsen** [comment]
Klopt DIA heeft in een pilot getest of de VSE gestructureerd kan uitgeleverd worden. Het project DIA  heeft het voorstel om tot implementatie over te gaan.

**Comment by ElisabethKloren** [comment]
Uitwisselformaat: klein beginnen, praktisch toepassen - liever betekenisvol (XML) dan CSV.

**Comment by TinovdGiesen** [comment]
> Informatiemodel van Relatics wisselt per project en opdrachtgever/-nemer. Dat is de kracht ervan, maar de betekenis van die data daarmee niet gewaarborgd.
> 
De informatie onder de motorkap maakt toch wel gebruik van dezelfde data velden. Daarmee wordt toch los van de verschijningsvorm de informatie wel overgedragen.

**Comment by ElisabethKloren** [comment]
User story voor beheercommissie

1.	Omschrijving van de vraag/opmerking zelf (bij voorkeur in het format van ‘userstory’):
Als  opdrachtgever, en (MKB) opdrachtnemer  in kleinere projecten
wil ik  een eenvoudig uitwisselformaat, die door een relatieve leek opgesteld en gelezen kan worden
zodat ik deze eenvoudig zelf kan opstellen en in mijn systemen kan inlezen
2.	Naam, functie (soort gebruiker/rol), diens organisatie, en de soort organisatie van de vraagsteller (stakeholder)
3.	Datum en oorsprong van het verzoek - Gebruikersbijeenkomst Contract als data 2 april 2020
4.	Wat is de urgentie  )
‘M’	(must have; hindert de dagelijkse procesgang/doorgang van een project; moet zo spoedig mogelijk worden opgelost)
5.	Toelichting op de urgentie* - een direct toepasbaar en haalbaar uitwisselformaat ontbreekt.

Voeg meer details toe:
1.	Het is een verbetervoorstel

3.	Verbetervoorstel
a.	Maak de userstory expliciet; mogelijk valt die uiteen in meerdere user stories 
Gedacht wordt aan Tim Berners'Lee, Niveau 3: Bestanden in open formaat: CSV, XML (dat wordt als eenvoudiger leesbaar aangeduid dan RDF)
b.	Beschrijf de randvoorwaarden 
-
c.	Completeer de ‘definiton of ‘done’ 
-

**Comment by ElisabethKloren** [comment]
Voortschrijdend inzicht: door een combinatie van een informatiemodel in linked data (op basis van NEN 2660) en de vertaling / binding naar een uitwisselformaat, kunnen op elk niveau afspraken gemaakt worden. In de technische documentatie wordt gestart met uitwisseling in een tabel.
